networks:
  grafana:
    driver: overlay
    attachable: true
  loki:

volumes:
  grafana-storage:
    name: grafana
    driver: local
    driver_opts:
      type: none
      device: /mnt/gluster/grafana
      o: bind
  prometheus-storage:
    name: prometheus
    driver: local
    driver_opts:
      type: none
      device: /mnt/gluster/prometheus
      o: bind
  loki-s3:
    name: loki
    driver: local
    driver_opts:
      type: none
      device: /mnt/gluster/loki
      o: bind

services:
  loki-backend:
    image: grafana/loki:latest
    deploy:
      resources:
        limits:
          memory: "200M"
        reservations:
          memory: "150M"
      restart_policy:
        condition: any
    volumes:
      - ./server/loki-config.yaml:/etc/loki/config.yaml
    command: "-config.file=/etc/loki/config.yaml -target=backend -legacy-read-mode=false"
    depends_on:
      - loki-proxy
    healthcheck:
      test: [  "CMD", "loki", "-health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - loki


  loki-read:
    image: grafana/loki:latest
    command: "-config.file=/etc/loki/config.yaml -target=read"
    deploy:
      resources:
        limits:
          memory: "200M"
        reservations:
          memory: "150M"
      restart_policy:
        condition: any
    volumes:
      - ./server/loki-config.yaml:/etc/loki/config.yaml
    depends_on:
      - minio
    healthcheck:
      test: [  "CMD", "loki", "-health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - loki

  loki-write:
    image: grafana/loki:latest
    command: "-config.file=/etc/loki/config.yaml -target=write"
    deploy:
      resources:
        limits:
          memory: "500M"
        reservations:
          memory: "250M"
      restart_policy:
        condition: any
    volumes:
      - ./server/loki-config.yaml:/etc/loki/config.yaml
    healthcheck:
      test: [ "CMD", "loki", "-health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - minio
    networks:
      - loki

  loki-proxy:
    image: nginx:latest
    deploy:
      resources:
        limits:
          memory: "24M"
        reservations:
          memory: "16M"
      restart_policy:
        condition: any
    depends_on:
      - loki-read
      - loki-write
    volumes:
      - ./server/loki-nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3100:3100"
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - loki
      - grafana

  # Might be moving this to garage (https://github.com/deuxfleurs-org/garage) as minio community support is ending .
  # have already tested garage and believe it would be a good replacement for this.
  minio:
    image: minio/minio:latest
    deploy:
      resources:
        limits:
          memory: "500M"
        reservations:
          memory: "250M"
      restart_policy:
        condition: any
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler && \
        minio server /data
    environment:
      - MINIO_ROOT_USER=loki
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    volumes:
      - loki-s3:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 15s
      timeout: 20s
      retries: 5
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    deploy:
      resources:
        limits:
          memory: "500M"
        reservations:
          memory: "250M"
      restart_policy:
        condition: any
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - TENANT_ID=${TENANT_ID}
    depends_on:
      - loki-proxy
      - prometheus
    volumes:
      - ./server/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/ds.yaml
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - grafana

  prometheus:
    image: prom/prometheus
    deploy:
      resources:
        limits:
          memory: "500M"
        reservations:
          memory: "250M"
      restart_policy:
        condition: any
    ports:
      - "9090:9090"
    volumes:
      - prometheus-storage:/prometheus
      - ./server/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
    healthcheck:
      test: [ "CMD-SHELL", "/bin/wget --no-verbose --tries=1 --spider http://localhost:9090/-/healthy || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - grafana
